default['chef-rean-sample-spring-application']['download_path'] = 'https://github.com/tahirstamboli/demo-spring-application/raw/master/sampleapplication-2.0.0.jar'
default['chef-rean-sample-spring-application']['db_user'] = 'root'
default['chef-rean-sample-spring-application']['db_password'] = 'Root@12345'
default['chef-rean-sample-spring-application']['db_name'] = 'demo'
default['chef-rean-sample-spring-application']['port'] = '9191'
default['chef-rean-sample-spring-application']['application_context'] = 'SpringBootCRUDApp'
default['chef-rean-sample-spring-application']['host'] = 'localhost'
default['chef-rean-sample-spring-application']['enable_firewall_port'] = ''
