default['chef-rean-sample-spring-application']['download-path'] = 'https://github.com/tahirstamboli/demo-spring-application/raw/master/sampleapplication-2.0.0.jar'
default['chef-rean-sample-spring-application']['db-user'] = 'root'
default['chef-rean-sample-spring-application']['db-password'] = 'Root@12345'
default['chef-rean-sample-spring-application']['db-name'] = 'demo'
default['chef-rean-sample-spring-application']['port'] = '9191'
default['chef-rean-sample-spring-application']['application-context'] = 'SpringBootCRUDApp'
default['chef-rean-sample-spring-application']['host'] = 'localhost'
